plugins {
    id "com.android.application"
}

android {
    namespace "com.murwy.ssoma.digital"
    compileSdk 35

    defaultConfig {
        applicationId "com.murwy.ssoma.digital"
        minSdk 23
        targetSdk 35
        versionCode 20000
        versionName "2.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "com.google.androidbrowserhelper:androidbrowserhelper:2.7.3"
}
